export const ErrorCodes = {
	NETWORK_ERROR: 'NETWORK_ERROR',
	AUTH_ERROR: 'AUTH_ERROR',
	VALIDATION_ERROR: 'VALIDATION_ERROR',
	COMPUTATION_ERROR: 'COMPUTATION_ERROR',
	TIMEOUT_ERROR: 'TIMEOUT_ERROR',
	CORS_ERROR: 'CORS_ERROR',
	UNKNOWN_ERROR: 'UNKNOWN_ERROR',
	INVALID_STATE: 'INVALID_STATE',
	INVALID_INPUT: 'INVALID_INPUT',
	INVALID_CONFIG: 'INVALID_CONFIG',
	BROWSER_ONLY: 'BROWSER_ONLY',
	ENVIRONMENT_ERROR: 'ENVIRONMENT_ERROR',
	ENCODING_ERROR: 'ENCODING_ERROR'
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
