import { downloadFileData } from '@/core/files/handle-files';
import { FileBaseInfo, FileData } from '@/core/files/types';
import type { MeshExtractionOptions } from '@/features/visualization/webdisplay/types';
import { RhinoComputeError, ErrorCodes } from '@/core/errors';

import { GrasshopperComputeResponse } from '../types';

import {
	extractFileData,
	getValue,
	getValues,
	GetValuesOptions,
	GetValuesResult,
	ParsedContext
} from '../io/output/response-processors';

/**
 * High-level wrapper for interacting with Grasshopper Compute responses.
 *
 * This class exposes a clean, consistent API for accessing parsed values,
 * geometry, and produced files. It is designed to be the primary interface
 * when working with Grasshopper results in client applications.
 */
export default class GrasshopperResponseProcessor {
	constructor(
		private readonly response: GrasshopperComputeResponse,
		private readonly debug: boolean = false
	) {}

	/**
	 * Extract all values in the response.
	 *
	 * @typeParam T - Expected structure of the return value. Defaults to a simple key/value map. (later cast as needed)
	 * @param byId - Key by parameter ID instead of name. Requires the VektorNode rhino.compute branch.
	 * @param options - Controls parsing behavior such as Rhino geometry decoding.
	 * @returns Parsed Grasshopper output values.
	 *
	 * @example
	 * ```ts
	 * const processor = new GrasshopperResponseProcessor(response);
	 * const { values } = processor.getValues();
	 * ```
	 *
	 * @example
	 * ```ts
	 * const { values } = processor.getValues(true); // keyed by param ID
	 * ```
	 */
	public getValues<T = ParsedContext>(
		byId: boolean = false,
		options: GetValuesOptions = {}
	): GetValuesResult<T> {
		return getValues<T>(this.response, byId, options);
	}

	/**
	 * Retrieve a specific value by parameter name or ID.
	 *
	 * @param selector - `{ byName }` for the human-readable name, `{ byId }` for the parameter GUID.
	 * @param options - Parsing configuration (e.g. disable parsing or enable Rhino).
	 * @returns Single parsed value, array of values, or undefined if the parameter is absent.
	 *
	 * `byId` requires the VektorNode rhino.compute branch.
	 *
	 * @example
	 * ```ts
	 * const schema = processor.getValue({ byName: 'Schema' });
	 * const output = processor.getValue({ byId: 'a4be1c1e-23f9-4c27-b942-7f3bb2c45c6f' });
	 * ```
	 */
	public getValue(
		selector: { byName: string } | { byId: string },
		options?: GetValuesOptions
	): any {
		return getValue(this.response, selector, options);
	}

	/**
	 * Decode all geometry results into Three.js meshes/lines ready for rendering.
	 * The processor's `debug` flag is merged with `options` (explicit options win).
	 *
	 * Requires the **Selva Display** Grasshopper component and the VektorNode
	 * rhino.compute branch. Three.js is loaded dynamically, so install it as a
	 * peer dependency before calling this.
	 *
	 * @throws {RhinoComputeError} If the three.js visualization module can't load.
	 *
	 * @example
	 * ```ts
	 * const meshes = await processor.extractMeshesFromResponse();
	 * scene.add(...meshes);
	 * ```
	 */
	public async extractMeshesFromResponse(options?: MeshExtractionOptions) {
		const mergedOptions: MeshExtractionOptions = {
			debug: this.debug,
			...options
		};

		// Dynamically import visualization module to avoid coupling three.js at module load time.
		// Narrow the try/catch to the import only — errors from mesh extraction itself should
		// propagate so callers can debug them, not get re-wrapped as "failed to load".
		let getThreeMeshesFromComputeResponse: typeof import('@/features/visualization').getThreeMeshesFromComputeResponse;
		try {
			({ getThreeMeshesFromComputeResponse } = await import('@/features/visualization'));
		} catch (error) {
			throw new RhinoComputeError(
				'Failed to load three.js visualization module. Ensure three.js is installed as a peer dependency.',
				ErrorCodes.INVALID_STATE,
				{
					context: { originalError: error instanceof Error ? error.message : String(error) }
				}
			);
		}

		return getThreeMeshesFromComputeResponse(this.response, mergedOptions);
	}

	/**
	 * Raw file entries packaged in the response (textures, JSON, CAD exports, …).
	 * Produced by the Selva **Block to File** / **Geometry To File** components on
	 * the VektorNode rhino.compute branch.
	 */
	private getFileData(): FileData[] {
		return extractFileData(this.response);
	}

	/**
	 * Download all files generated by Grasshopper, optionally including
	 * additional user-provided files.
	 *
	 * Files are grouped under the specified folder name when downloaded.
	 *
	 * @param folderName - Name for the download directory.
	 * @param additionalFiles - Extra files to package (single file, array, or null).
	 *
	 * @example
	 * ```ts
	 * await processor.getAndDownloadFiles('gh-output');
	 * ```
	 *
	 * @example
	 * ```ts
	 * const extra = { name: 'notes.txt', data: 'Example' };
	 * await processor.getAndDownloadFiles('project', extra);
	 * ```
	 */
	public async getAndDownloadFiles(
		folderName: string,
		additionalFiles?: FileBaseInfo[] | FileBaseInfo | null
	): Promise<void> {
		const files = this.getFileData();
		await downloadFileData(files, folderName, additionalFiles);
	}
}
